package com.rdc.drawing.board.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.rdc.drawing.bean.SaveData;

import com.rdc.drawing.board.dao.SaveDataDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig saveDataDaoConfig;

    private final SaveDataDao saveDataDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        saveDataDaoConfig = daoConfigMap.get(SaveDataDao.class).clone();
        saveDataDaoConfig.initIdentityScope(type);

        saveDataDao = new SaveDataDao(saveDataDaoConfig, this);

        registerDao(SaveData.class, saveDataDao);
    }
    
    public void clear() {
        saveDataDaoConfig.clearIdentityScope();
    }

    public SaveDataDao getSaveDataDao() {
        return saveDataDao;
    }

}
